### PR TITLE
Update README.md, remove link to Stream Matchers

### PR DESCRIPTION
**Pull request by srawlins**
This section was removed: https://github.com/dart-lang/test/commit/cc0598b2c3bf3a7439f10f9542a8d01ff50b69e9#diff-c97f9e0d4b6adec304ed041e0063f78a4842c22d03bcaa5086a66c9d49aeab98

I have no idea what else should be removed or added from the ToC, and I have no idea how you would maintain this ToC.

Fixes https://github.com/dart-lang/test/issues/2188

---

- [x] I’ve reviewed the contributor guide and applied the relevant portions to this PR.

<details>
  <summary>Contribution guidelines:</summary><br>

- See our [contributor guide](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md) for general expectations for PRs.
- Larger or significant changes should be discussed in an issue before creating a PR.
- Contributions to our repos should follow the [Dart style guide](https://dart.dev/guides/language/effective-dart) and use `dart format`.
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/wiki/External-Package-Maintenance#making-a-change).
- Changes to packages require [corresponding tests](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md#Testing).

Note that many Dart repos have a weekly cadence for reviewing PRs - please allow for some latency before initial review feedback.
</details>

### CODE REVIEW

**Comment by srawlins** [comment]
OK, I'll just close and open an issue instead.

**Comment by jakemac53** [comment]
Re-opened and uploaded the changelog/pubspec edits

**Comment by jakemac53** [comment]
Added Nate to approve those just so I am not approving my own stuff :rofl:

**Comment by srawlins** [comment]
Thanks!

**Pull request merged**
