### PR TITLE
[pkg:test] Fix binary location of Firefox on Mac

### PR DESCRIPTION
**Pull request by kevmoo**

### CODE REVIEW

**Comment by kevmoo** [comment]
@jakemac53 – thoughts on this?

**Comment by jakemac53** [comment]
> @jakemac53 – thoughts on this?

I have no context so I have no thoughts :). Did it move? Does this location work on older versions? Maybe we need a fallback to the old location etc...

**Comment by kevmoo** [comment]
it DID move @jakemac53

FF tests were failing locally until I made this fix.
I guess I can open an issue that we actually test FF + Mac in CI, right?

**Comment by jakemac53** [comment]
> I guess I can open an issue that we actually test FF + Mac in CI, right?

I don't know if anybody has the bandwidth to actually look into this, there might be an open issue already.

**Comment by jakemac53** [comment]
See also https://github.com/dart-lang/test/issues/2194 and https://github.com/dart-lang/test/pull/2195 ... the tldr; here is that it seems like adding support for multiple paths was never agreed upon and no matter what we do it doesn't work for some people.

But, maybe this change has existed for long enough that it is time to make the switch, and highlight the workaround for anybody on older versions (using a custom path for Firefox via dart_test.yaml).

cc @natebosch thoughts?

**Comment by natebosch** [comment]
https://github.com/dart-lang/test/pull/2276 gives a try at making this non-breaking and keeping the scope of the change as small as possible.

I haven't tested it yet, but I can if we think we want to land it.
I'm 50/50 on whether I want to try to land something minimal like that, or to just make the switch assuming more users will benefit than suffer, and document the workaround.

Do we have any details on when it moved, or how many users are likely to have either path?

**Comment by kevmoo** [comment]
Happy to run with #2276 if that's good.

Want me to close this?

**Pull request closed without merging**
