### PR TITLE
Convert JS stack traces into Dart stack traces.

### LINKED ISSUE #21: Use source maps to Dartify browser stack traces
Once we support browser tests, we should use the source maps generated by dart2js to convert their JS stack traces back into Dart traces. @cbracken has some code to do this, but it's not currently written in Dart.

### PR DESCRIPTION
**Pull request by nex3**
Closes #21

[Review on Reviewable](https://reviewable.io/reviews/dart-lang/test/117)

### CODE REVIEW

**Comment by kevmoo** [comment]
LGTM

---

Review status: 0 of 11 files reviewed, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dart-lang/test/117)

**Comment by kevmoo** [comment]
Review status: 0 of 11 files reviewed, 1 unresolved discussion, all commit checks successful.

---

<sup>**[lib/src/util/io.dart, line 8 \[r1\]](https://reviewable.io:443/reviews/dart-lang/test/117#-JpdojC5N82Em6c2RavB)** ([raw file](https://github.com/dart-lang/test/blob/6293cc965873134b4eb6a6f478e67346ddf235e7/lib/src/util/io.dart#L8)):</sup>
Needed?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dart-lang/test/117)

**Comment by kevmoo** [comment]
Review status: all files reviewed, 1 unresolved discussion, all commit checks successful.
Reviewed files:
- CHANGELOG.md @ r1
- lib/src/executable.dart @ r1
- lib/src/runner/browser/browser_manager.dart @ r1
- lib/src/runner/browser/iframe_test.dart @ r1
- lib/src/runner/browser/server.dart @ r1
- lib/src/runner/loader.dart @ r1
- lib/src/util/io.dart @ r1
- lib/src/util/stack_trace_mapper.dart @ r1
- pubspec.yaml @ r1
- test/runner/browser/runner_test.dart @ r1
- test/runner/pub_serve_test.dart @ r1

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dart-lang/test/117)

**Comment by nex3** [comment]
Review status: all files reviewed, 1 unresolved discussion, all commit checks successful.

---

<sup>**[lib/src/util/io.dart, line 8 \[r1\]](https://reviewable.io:443/reviews/dart-lang/test/117#-JpdojC5N82Em6c2RavB)** ([raw file](https://github.com/dart-lang/test/blob/6293cc965873134b4eb6a6f478e67346ddf235e7/lib/src/util/io.dart#L8)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dart-lang/test/117)

**Comment by kevmoo** [comment]
Review status: :shipit: all files reviewed, all discussions resolved, all commit checks successful.
Reviewed files:
- lib/src/util/io.dart @ r2

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dart-lang/test/117)

**Pull request merged**
