### PR TITLE
Flush stdin after writing in pause after load test

### PR DESCRIPTION
**Pull request by natebosch**
Towards #1613

Try unskipping this test on windows.

### CODE REVIEW

**Comment by natebosch** [comment]
```
Process `dart bin/test.dart` was killed with SIGKILL in a tear-down. Output:
      00:00 +0: compiling test1.dart
      Info: Compiling with sound null safety
      Compiled 10,753,036 characters Dart to 1,205,090 characters JavaScript in 5.80 seconds using 318.363 MB of memory
      Dart file ../dart_test_8c1b4cee/runInBrowser.dart compiled to JavaScript: ../dart_test_49d7aed0/test_f15e72c3/test1.dart.browser_test.dart.js
      
      loaded test 1!
      
      The test runner is paused. Open the dev console in Chrome and set breakpoints. Once you're finished, return to this terminal and press Enter.
      00:00 +0: test1.dart: success
      00:00 +1: compiling test2.dart
      Info: Compiling with sound null safety
      Compiled 10,753,036 characters Dart to 1,205,090 characters JavaScript in 6.70 seconds using 315.223 MB of memory
      Dart file ../dart_test_a03e4eb0/runInBrowser.dart compiled to JavaScript: ../dart_test_49d7aed0/test_cfc8df22/test2.dart.browser_test.dart.js
      
      loaded test 2!
      
      The test runner is paused. Open the dev console in Chrome and set breakpoints. Once you're finished, return to this terminal and press Enter.
      00:09 +1: test2.dart: success
      00:09 +2: All tests passed!
  Retry: pauses the test runner for each file until the user presses enter
  
// 8<----------
// snip the same process was killed output 3 more times
// 8<----------
  TimeoutException after 0:02:00.000000: Test timed out after 2 minutes.
  package:test_api/src/backend/invoker.dart 338:28  Invoker._handleError.<fn>
  dart:async                                        _CustomZone.run
  package:test_api/src/backend/invoker.dart 336:10  Invoker._handleError
  package:test_api/src/backend/invoker.dart 291:9   Invoker.heartbeat.<fn>.<fn>
  dart:async                                        _CustomZone.run
  package:test_api/src/backend/invoker.dart 290:38  Invoker.heartbeat.<fn>
  FileSystemException: Deletion failed, path = 'C:\Users\runneradmin\AppData\Local\Temp\dart_test_b00e54' (OS Error: The process cannot access the file because it is being used by another process.
  , errno = 32)
  package:test_descriptor  sandbox.<fn>
  TimeoutException after 0:02:00.000000: Test timed out after 2 minutes.
  package:test_api/src/backend/invoker.dart 338:28  Invoker._handleError.<fn>
  dart:async                                        _CustomZone.run
  package:test_api/src/backend/invoker.dart 336:10  Invoker._handleError
  package:test_api/src/backend/invoker.dart 291:9   Invoker.heartbeat.<fn>.<fn>
  dart:async                                        _CustomZone.run
  package:test_api/src/backend/invoker.dart 290:38  Invoker.heartbeat.<fn>
  TimeoutException after 0:02:00.000000: Test timed out after 2 minutes.
  package:test_api/src/backend/invoker.dart 338:28  Invoker._handleError.<fn>
  dart:async                                        _CustomZone.run
  package:test_api/src/backend/invoker.dart 336:10  Invoker._handleError
  package:test_api/src/backend/invoker.dart 291:9   Invoker.heartbeat.<fn>.<fn>
  dart:async                                        _CustomZone.run
  package:test_api/src/backend/invoker.dart 290:38  Invoker.heartbeat.<fn>
  TimeoutException after 0:02:00.000000: Test timed out after 2 minutes.
  package:test_api/src/backend/invoker.dart 338:28  Invoker._handleError.<fn>
  dart:async                                        _CustomZone.run
  package:test_api/src/backend/invoker.dart 336:10  Invoker._handleError
  package:test_api/src/backend/invoker.dart 291:9   Invoker.heartbeat.<fn>.<fn>
  dart:async                                        _CustomZone.run
  package:test_api/src/backend/invoker.dart 290:38  Invoker.heartbeat.<fn>
```

**Comment by natebosch** [comment]
I don't understand the failure output, how does it happen that we get only 1 timeout, but 4 times with the process running and getting killed? What is causing it to get killed 4 times if not a timeout?

Or do we only show 1 failure when we retry?

**Comment by natebosch** [comment]
Also, how do we get a test that `(failed after test completion)` when the stack trace points to a future that is awaited within the test body. How can this surface after test completion?

https://github.com/dart-lang/test/blob/6f215fe71d7767aebccd88ce2024a1253edca30e/pkgs/test/test/runner/pause_after_load_test.dart#L245

```
test\runner\pause_after_load_test.dart: disables timeouts (failed after test completion)
  Expected: <0>
    Actual: <-1>
  Process `dart bin/test.dart` had an unexpected exit code.
  
  package:test_api/src/expect/expect.dart 134:31    fail
  package:test_api/src/expect/expect.dart 129:3     _expect
  package:test_api/src/expect/expect.dart 46:3      expect
  ===== asynchronous gap ===========================
  test\runner\pause_after_load_test.dart 245:5      main.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/declarer.dart 215:9  Declarer.test.<fn>.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/declarer.dart 213:7  Declarer.test.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/invoker.dart 258:9   Invoker._waitForOutstandingCallbacks.<fn>
```

**Comment by natebosch** [comment]
It does seem like the subprocess doesn't end, because it needs to get killed and then exits with `-1` despite it reporting that all tests passed.

**Comment by mosuem** [comment]
Closing this, as it is stale and the files are out of date. Feel free to reopen in case you still want to land it!

**Pull request closed without merging**
