### PR TITLE
Disable dartfmt travis tests

### PR DESCRIPTION
**Pull request by natebosch**

### CODE REVIEW

**Comment by natebosch** [comment]
It's not clear this will continue to be the style - https://github.com/dart-lang/dart_style/issues/799

We want to get travis green for now.

**Comment by kevmoo** [comment]
Or just ignore it until the fix is rolled – @munificent is working on it now

**Comment by kevmoo** [comment]
PR in flight. I'd just skip it for now?

**Comment by kevmoo** [comment]
https://github.com/dart-lang/dart_style/pull/800

**Comment by natebosch** [comment]
> I'd just skip it for now?

I suppose. The nice thing about reformatting and then formatting back is that we can't forget about it...

If we skip the test we might forget to re-enable.

**Comment by jakemac53** [comment]
fwiw I much prefer keeping the test and just accepting the new formatting - we will immediately know when we can fix it again. This is a lot more likely to remain "skipped" well beyond when the issue is fixed because we get zero signal about it when the fix lands.

**Comment by kevmoo** [comment]
> fwiw I much prefer keeping the test and just accepting the new formatting - we will immediately know when we can fix it again. This is a lot more likely to remain "skipped" well beyond when the issue is fixed because we get zero signal about it when the fix lands.

There is a new dev SDK out w/ the "right fix". Just need to go through and enable formatting on dev-only and we should be good!

**Pull request merged**
