### PR TITLE
Explicitly exit after tests are run

### PR DESCRIPTION
**Pull request by grouma**

### CODE REVIEW

**Comment by grouma** [comment]
Related to https://github.com/dart-lang/test/issues/599

**Comment by natebosch** [comment]
Feels hacky - are we going to keep digging on the root cause?

**Comment by grouma** [comment]
Yes. There are tons of unawaited futures in the package though so it may take a while to track down. Lets discuss when you are in the office on potential ways to track down the offending future.

**Comment by Hixie** [comment]
FYI this patch broke Flutter because we have code that calls the test package's `main()` method and tries to do extra work (most notably collecting coverage) afterwards, and instead now our script just exits suddenly. We're pinning to an earlier version for now, but do you have a recommended alternative solution we should use?

**Comment by natebosch** [comment]
@grouma I think I remember you making some progress on this - do you know if we'll be able to drop the explicit exit now?

**Comment by grouma** [comment]
I had thought I resolved some flakiness but unfortunately couldn't pinpoint the root cause. I added a fix after this patch to only explicitly close on Travis. Update to the latest version and you shouldn't have issues.

**Comment by natebosch** [comment]
> Update to the latest version and you shouldn't have issues.

Except on Travis...

**Comment by Hixie** [comment]
Yeah, on Travis is where we ran into this.

**Comment by grouma** [comment]
Spoke with Jacob and he explained the situation. Sorry for the confusion. My belief right now is that the flakiness comes only from the tests inside package:test. We have a couple levels of indirection in which we spin up a test runner which spins up another test runner etc. Things may have gotten better recently with some of the refactors and Natalie's changes. I'll do some experimentation and see if we can remove the hack all together. If not I'll use a custom flag which we'll set only in our Travis configuration. Expect a new version some time tomorrow.

**Pull request merged**
