### PR TITLE
Bump min Dart version to 3.4.0 for WASM

### PR DESCRIPTION
**Pull request by Rexios80**
Before 3.4.0:
```console
  Could not find an option with short name "-O".
  
  Usage: dart compile wasm [arguments] <dart entry point>
```

This option was added in commit [92d53c426f9b4764e5c34d33ef7bbcf5fd3b12a6](https://github.com/dart-lang/sdk/commit/92d53c426f9b4764e5c34d33ef7bbcf5fd3b12a6)

### CODE REVIEW

**Comment by jakemac53** [comment]
Thanks, unfortunately we can't fix this for the old published versions, and are past the retraction window for 1.25.6. Because of that I won't bother publishing this change right now, but we should land it nonetheless.

**Comment by jakemac53** [comment]
adding @natebosch for additional review since I pushed a bunch of other related changes here

**Comment by Rexios80** [comment]
Should we update CI to run at the lowest resolvable Dart SDK version to avoid this in the future?

**Comment by jakemac53** [comment]
> Should we update CI to run at the lowest resolvable Dart SDK version to avoid this in the future?

It does already - the problem is wasm is tested through the `integration_tests/wasm/` package, which _was_ updated to require 3.4.0. This was just missed in code review.

We should also add at least a basic wasm test in the actual `test` package probably though.

**Review by natebosch — APPROVED** [review]

**Comment by jakemac53** [comment]
It looks like these failures are a result of the change to running on `3.4.0`, so something has changed such a that only certain tests now fail on windows.

We will separately address this problem, landing this for now, on red.

**Pull request merged**
