### PR TITLE
Attempt at forwards compatible fix for pre-nnbd branch tests

### PR DESCRIPTION
**Pull request by jakemac53**
Updates the default package config for tests so that it adds an entry for the sandbox dir.

- Sets the default language version to that of the test package.

### CODE REVIEW

**Comment by jakemac53** [comment]
I am not sure what we want to do about the hybrid tests - we could possibly change the ones that actually run to instead import an opted out library, and expect that the spawning fails due to running in strong mode.

That should be able to pass in both the master and pre-nnbd branches?

**Review by natebosch — APPROVED** [review]

**Comment by natebosch** [comment]
> we could possibly change the ones that actually run to instead import an opted out library, and expect that the spawning fails due to running in strong mode.

I'm not sure I understand. We do need some to run. Which test cases specifically were you thinking of changing in this way?

**Comment by jakemac53** [comment]
> We do need some to run.

Yes, agreed that we need to ensure you can communicate back and forth. But all those tests would be ran in opted out mode to be compatible.

> Which test cases specifically were you thinking of changing in this way?

Any hybrid test which runs in opted in mode (anything with a data uri or that runs a non-opted out script in a sandbox dir).

**Comment by natebosch** [comment]
I think the only thing we couldn't catch that way would be for being able to successfully run with opt in, which does exercise some behavior that could be broken in strong mode. I don't know how likely we are to break the code in that way specifically that would be caught.

**Comment by jakemac53** [comment]
Ya my sense is that it would be pretty unlikely. We will have confirmation that it can _attempt_ to run in strong mode, and that it can successfully run in weak mode.

To me, the value of being able to test the `pre-nnbd` branch would outweigh the negatives.

**Comment by jakemac53** [comment]
Alternatively, we could land this as is (and merge it into master with the changelog entry). It still fixes a lot of tests and we could hand analyze the remaining failures each time.

**Comment by natebosch** [comment]
Could we skip the test on the `pre-nnbd` branch? Maybe with a tag, or a hardcoded boolean variable or something? Then when merging in to master we'd be careful to keep that different between the two branches?

**Comment by jakemac53** [comment]
We could skip the tests, but the spawn hybrid apis are where a bunch of fixes have gone - so I would like to have test coverage for it.

You also wouldn't get a merge conflict I don't think - depending on how it was done. So that could make it harder to remember to revert those changes.

**Pull request closed without merging**
