### PR TITLE
add webhook notifications to chat for failed builds

### PR DESCRIPTION
**Pull request by jakemac53**
Update to latest mono_repo and use the `on_completion` support to ping our chat for failed push/scheduled builds.

Also added a cron job.

### CODE REVIEW

**Review by kevmoo — APPROVED** [review]
Deleted `.travis.yml` while you're at it?

**Comment by kevmoo** [comment]
> Deleted `.travis.yml` while you're at it?

and `tool/report_failure.sh`

**Comment by jakemac53** [comment]
We still use travis also, might drop that separately

**Comment by jakemac53** [comment]
Actually nvm, it doesn't look like we do bleeding edge tests on travis so ill just drop it.

**Pull request merged**
