### PR TITLE
Record the working directory for VM platform

### PR DESCRIPTION
**Pull request by natebosch**
Towards #1803

A VM test can change the working directory for the entire process. If this happens it will change the result for the absolute path against the relative paths provided to the VM platform plugin.

Record `Directory.current` when the platform plugin is instantiated. Any place where an absolute path is needed attempt to resolve against the original working directory.

Move some top-level methods into the plugin so they can read the cached working directory.

### CODE REVIEW

**Comment by natebosch** [comment]
@jakemac53 - if you are OK with the approach I can work on adding tests and extending it to the browser and node platforms.

**Comment by jakemac53** [comment]
Oh actually I realize now this needs to be done on all platforms since any vm test could break browser/node/etc tests.

**Comment by jakemac53** [comment]
Another question - do we instantiate all platforms early on before running any tests? Or do we do it more lazily when a test is run? If the latter we would need to do this earlier before any test is ran and pass it to all the plugins.

**Comment by natebosch** [comment]
> Another question - do we instantiate all platforms early on before running any tests? Or do we do it more lazily when a test is run? If the latter we would need to do this earlier before any test is ran and pass it to all the plugins.

Unfortunately it seems we instantiate them lazily.

I hope to avoid needing to change the API between the runner and test platforms, I wonder if we can get away with more eagerly instantiating them.

cc @christopherfujino - I don't think we have any situations where the flutter test platform is used in the same runner as the VM test platform - do we? I think `flutter test` shouldn't be impacted by this, but you might know better than me.

**Comment by natebosch** [comment]
> I wonder if we can get away with more eagerly instantiating them.

This does not appear very feasible without some significant refactoring.

**Comment by natebosch** [comment]
@jakemac53 - WDYT about moving forward with this workaround for the VM platform, and punting on a full solution for now? This is feeling fairly involved, and as it stands there is really not much workaround for impacted users beyond "Don't change directories without changing it back". If we ship this, it should let impacted users have a workaround of separating runs of VM platform from other platforms.

**Comment by jakemac53** [comment]
I am fine with moving forward with this just for the VM platform.

**Review by jakemac53 — APPROVED** [review]

**Pull request merged**
