### PR TITLE
Require analyzer 5.12.0, refactor InstanceCreationExpression type name extraction.

### PR DESCRIPTION
**Pull request by scheglov**
As requested in https://github.com/dart-lang/test/issues/2013

### CODE REVIEW

**Comment by natebosch** [comment]
Looks like we  need to drop support for Dart 2.x for this. I will handle that in a separate PR after confirming we are ready for that.

Thanks @scheglov for the quick fix!

**Comment by scheglov** [comment]
Any news? I'd like to roll the breaking change to the analyzer, and this requires these changes to `test_core`.

**Comment by natebosch** [comment]
I've started the switch to Dart 3.0.0 in https://github.com/dart-lang/test/pull/2024

**Review by natebosch — APPROVED** [review]

**Comment by natebosch** [comment]
Thank you for the fix!

**Pull request merged**
