### PR TITLE
Stop importing dart:io from browser libraries

### LINKED ISSUE #781: Exception running coverage in content-shell (Dart 1.24.3)
fyi @nex3:
We believe the latest release's inclusion of https://github.com/dart-lang/test/pull/779 is breaking CI for us in a number of (maybe all of?) our Dart repos.  Pinning to test `<0.12.32` resolves the issue. We are seeing the following exceptions when attempting to run coverage in content-shell:

```
Uncaught Unhandled exception:
        'dart:io-patch/platform_patch.dart': error: line 12: native function 'Platform_OperatingSystem' (0 arguments) cannot be found
          static String _operatingSystem() native "Platform_OperatingSystem";
          ^

        #0      _Platform.operatingSystem (platform_impl.dart:60)
        #1      Platform._operatingSystem (platform.dart:71)
        #2      Platform._operatingSystem (platform.dart:71)
        #3      Platform.operatingSystem (platform.dart:95)
        #4      currentOS.<anonymous closure> (package:test/src/util/io.dart:46:23)
        #5      currentOS (package:test/src/util/io.dart:51:3)
        #6      currentOS (package:test/src/util/io.dart:45:23)
        #7      currentOSGuess.<anonymous closure> (package:test/src/utils.dart:59:43)
        #8      _ifSupported (package:test/src/utils.dart:97:20)
        #9      currentOSGuess (package:test/src/utils.dart:59:24)
        #10     currentOSGuess (package:test/src/utils.dart:59:7)
        #11     _declarer.<anonymous closure> (package:test/test.dart:66:17)
        <asynchronous suspension>
        #12     _microtaskLoop (dart:async/schedule_microtask.dart:41)
        #13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
        #14     _ScheduleImmediateHelper._handleMutation (dart:html:53852)", source: http://localhost:60720/browser/generated_runner.dart.temp.html (1)

### PR DESCRIPTION
**Pull request by nex3**
I forgot that this wasn't supported in Dart 1.24 😝.

Closes #781

### CODE REVIEW

**Comment by travissanderson-wf** [comment]
fwiw I have verified this branch passes in CI for us :)

**Comment by lrhn** [comment]
Which versions is it supported in?

**Comment by nex3** [comment]
@lrhn Unfortunately the changelog doesn't seem to mention it, so it's hard to tell.

**Comment by lrhn** [comment]
It was landed [a year ago](https://codereview.chromium.org/2675023002/), and I haven't heard that the feature was removed (and neither has @johnniwinther). Maybe it's a bug?

**Comment by nex3** [comment]
Maybe it didn't make it into content shell in particular?

**Pull request merged**
