### PR TITLE
Allow the next semver major versions of shelf_web_socket and web_socket_channel

### PR DESCRIPTION
**Pull request by brianquinlan**
This is part of a [plan to simplify the web_socket_channel implementation](https://github.com/dart-lang/web_socket_channel/issues/340)

---

- [X] I’ve reviewed the contributor guide and applied the relevant portions to this PR.

<details>
  <summary>Contribution guidelines:</summary><br>

- See our [contributor guide](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md) for general expectations for PRs.
- Larger or significant changes should be discussed in an issue before creating a PR.
- Contributions to our repos should follow the [Dart style guide](https://dart.dev/guides/language/effective-dart) and use `dart format`.
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/wiki/External-Package-Maintenance#making-a-change).
- Changes to packages require [corresponding tests](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md#Testing).

Note that many Dart repos have a weekly cadence for reviewing PRs - please allow for some latency before initial review feedback.
</details>

### CODE REVIEW

**Comment by jakemac53** [comment]
These versions do not yet look to be published, can we wait to land this until we are sure we are actually compatible?

If you just need to get a version solve in those packages tests, I would add a dependency override on this package.

Or, we could add a git dependency override in this package, to run the tests with the latest versions of those packages, but that isn't ideal because those packages could still change (as they haven't yet been published). So I would prefer the first option, and then publishing here once those are actually available and we can run with the newer versions on CI.

**Comment by brianquinlan** [comment]
@jakemac53 

> These versions do not yet look to be published, can we wait to land this until we are sure we are actually compatible?
> 
> If you just need to get a version solve in those packages tests, I would add a dependency override on this package.
> 
> Or, we could add a git dependency override in this package, to run the tests with the latest versions of those packages, but that isn't ideal because those packages could still change (as they haven't yet been published). So I would prefer the first option, and then publishing here once those are actually available and we can run with the newer versions on CI.

I probably don't understand some aspect of version solving, which is why I was using this approach.

`package:test` and `package:shelf_web_socket` depend on each other.

If I want to change the semver major version of `package:shelf_web_socket` (e.g. in this [PR](https://github.com/dart-lang/shelf/pull/423)), how can I use dependency overrides to allow its tests to run? If I change `self_web_socket/pubspec.yaml` to include:

```yaml
dependency_overrides:
  shelf_web_socket: ^2.0.0-wip
```

Then I get an error:
```
dart pub get --no-example
Resolving dependencies...
Error on line 25, column 3 of pubspec.yaml: A package may not list itself as a dependency.
   ╷
25 │   shelf_web_socket: ^2.0.0-wip
   │   ^^^^^^^^^^^^^^^^
   ╵
exit code 65
```

Any help would be appreciated!

**Comment by jakemac53** [comment]
@brianquinlan What you should do is override the version of `package:test`, in the shelf_web_socket etc packages:

```yaml
dependency_overrides:
  test: 1.25.2
```

You get a version solve error today because there is no version of `test` which declares compatibility with your local package, so overriding the version of package:test is what will fix that.

Then your local tests can run, and once you publish we can bump the constraints here.

**Comment by jakemac53** [comment]
Note that it is perfectly safe to publish with overridden dev dependencies, they do not affect your users (and in general, dependency_overrides do not affect your users, they are local only).

**Comment by brianquinlan** [comment]
> Note that it is perfectly safe to publish with overridden dev dependencies, they do not affect your users (and in general, dependency_overrides do not affect your users, they are local only).

Thanks!

**Comment by brianquinlan** [comment]
The plan is to release the following in rapid succession:
* package:web_socket_channel 3.0: removes WebSocketChannel constructor
* package:shelf_web_socket 2.0: doesn't use WebSocketChannel constructor, allow web_socket_channel >= 2 < 4
* package:test 1.26: allow web_socket_channel >= 2 < 4, allow shelf_web_socket >= 1 < 3

Does this package autopublish? I don't understand the validation failure.

**Comment by jakemac53** [comment]
> Does this package autopublish? I don't understand the validation failure.

It publishes based on tags - but because of our pinned deps we have to ignore the pub warnings by adding a label to PRs to make the validation step pass (I just did that though)

**Comment by brianquinlan** [comment]
> > Does this package autopublish? I don't understand the validation failure.
> 
> It publishes based on tags - but because of our pinned deps we have to ignore the pub warnings by adding a label to PRs to make the validation step pass (I just did that though)

Thanks!

Would it be possible to merge this and then do a release on Monday after I've release `package:web_socket_channel` and `package:shelf_web_socket`?

**Comment by jakemac53** [comment]
> Would it be possible to merge this and then do a release on Monday after I've release `package:web_socket_channel` and `package:shelf_web_socket`?

We would want to do the publish immediately after the merge - otherwise it puts us in a weird state.

**Comment by brianquinlan** [comment]
Right. So when is a good time for me to publish `shelf_web_socket` and `web_socket_channel` such that we can merge this and do a release quickly after?

If I release those packages now, can we release `package:test` in the next day or so?

**Comment by jakemac53** [comment]
> Right. So when is a good time for me to publish `shelf_web_socket` and `web_socket_channel` such that we can merge this and do a release quickly after?
> 
> If I release those packages now, can we release `package:test` in the next day or so?

Monday would probably be good, cc @natebosch

**Comment by natebosch** [comment]
A publish on Monday SGTM.

These have all been running in google3 right?

**Comment by brianquinlan** [comment]
Yes. They have been 

> A publish on Monday SGTM.
> 
> These have all been running in google3 right?

Yes, for almost 3 weeks now.

**Comment by jakemac53** [comment]
@brianquinlan sgtm

**Comment by brianquinlan** [comment]
>> I'm going to publish package:web_socket_channel and package: shelf_web_socket now.
> @brianquinlan sgtm

Done. Could someone merge this PR and publish `package:test`?

**Comment by jakemac53** [comment]
We are picking up the latest versions in the tests so that is good 👍

**Comment by brianquinlan** [comment]
> We are picking up the latest versions in the tests so that is good 👍

And the tests are passing, which is even better 🎉

**Comment by brianquinlan** [comment]
Can we submit and release?

**Review by jakemac53 — APPROVED** [review]

**Comment by jakemac53** [comment]
Done and done!

**Comment by brianquinlan** [comment]
Thanks so much!

**Pull request merged**
