### PR TITLE
Run no response daily

### PR DESCRIPTION
**Pull request by kevmoo**
Every hour is too much noise!

### CODE REVIEW

**Comment by kevmoo** [comment]
See 
image

**Review by devoncarew — APPROVED** [review]
lgtm; we should also update the template in dart-lang/ecosystem/pkgs/blast_repo.

**Comment by devoncarew** [comment]
https://github.com/dart-lang/ecosystem/pull/33

**Review by jakemac53 — APPROVED** [review]

**Comment by jakemac53** [comment]
landed on red - build is broken for other reasons

**Pull request merged**
