### PR TITLE
Create scorecards-analysis.yml

### PR DESCRIPTION
**Pull request by sealesj**
Enables scorecards for test repo as part security scanning effort on multiple dart-lang repos. Related issue for more context: https://github.com/dart-lang/.github/issues/16

scorecards-analysis.yaml generated through integration with OSSF Scorecards.

### CODE REVIEW

**Comment by jakemac53** [comment]
Looks like an existing failing test here, one of us can look into that separately.

**Review by jakemac53 — APPROVED** [review]
It would be nice to understand a bit more exactly what this is? There isn't much info in the linked issue.

But otherwise, LGTM

**Comment by sealesj** [comment]
@jakemac53 Yes hopefully to provide a bit more context for at least the scorecard process, enabling this scorecard analysis will allow for vulnerability alerting after scans triggered via a push to master. Then any vulnerabilities will be easily visible on the security tab and hopefully quickly remediated. Also not all repos in dart-lang are targeted to have this scorecard enabled, but rather just the top critical repos. The scorecard comes from this https://github.com/ossf/scorecard-action

**Comment by jakemac53** [comment]
Ok great, that link does help clarify things :).

I saw that it mentions it can also scan dependencies for issues, but I presume that would require some additional setup? We should also probably consider adding this check directly to the repos of all dependencies of package:test, which is quite a few?

**Comment by jakemac53** [comment]
fix is out for the failing test fwiw, https://github.com/dart-lang/test/pull/1696

**Comment by sealesj** [comment]
Could you help re-trigger the tests now that the fix is merged?

**Comment by devoncarew** [comment]
@sealesj - it looks like the new version of the scorecard-action needs additional permissions to run; see https://github.com/dart-lang/test/commit/3166163ee5e2c134feb5ebd5c803663a20930df8. I've updated this one and the one for dart-lang/sdk; perhaps you can update the others in dart-lang/?

**Comment by sealesj** [comment]
@devoncarew Ok great, I will update

**Comment by sealesj** [comment]
I verified on the other repos on which we added scorecards 
 github.com/dart-lang/linter
 github.com/dart-lang/sdk
 github.com/dart-lang/dartdoc
 github.com/dart-lang/site-www
and it looks like they all have this additional permission and have been running successfully

**Comment by devoncarew** [comment]
Great, thanks!

**Pull request merged**
