### PR TITLE
Convert most Future-based code to async/await

### PR DESCRIPTION
**Pull request by nex3**
[Review on Reviewable](https://reviewable.io/reviews/dart-lang/test/118)

### CODE REVIEW

**Comment by kevmoo** [comment]
See comments, especially String copy snafu. Otherwise, lgtm

---

Review status: all files reviewed, 4 unresolved discussions, some commit checks failed.
Reviewed files:
- lib/pub_serve.dart @ r1
- lib/src/backend/declarer.dart @ r1
- lib/src/backend/group.dart @ r1
- lib/src/backend/invoker.dart @ r1
- lib/src/backend/live_test_controller.dart @ r1
- lib/src/executable.dart @ r1
- lib/src/runner/browser/browser_manager.dart @ r1
- lib/src/runner/browser/chrome.dart @ r1
- lib/src/runner/browser/compiler_pool.dart @ r1
- lib/src/runner/browser/content_shell.dart @ r1
- lib/src/runner/browser/dartium.dart @ r1
- lib/src/runner/browser/firefox.dart @ r1
- lib/src/runner/browser/iframe_listener.dart @ r1
- lib/src/runner/browser/internet_explorer.dart @ r1
- lib/src/runner/browser/phantom_js.dart @ r1
- lib/src/runner/browser/safari.dart @ r1
- lib/src/runner/browser/server.dart @ r1
- lib/src/runner/browser/static/host.dart @ r1
- lib/src/runner/engine.dart @ r1
- lib/src/runner/loader.dart @ r1
- lib/src/runner/reporter/compact.dart @ r1
- lib/src/runner/reporter/expanded.dart @ r1
- lib/src/runner/vm/isolate_listener.dart @ r1
- lib/src/runner/vm/isolate_test.dart @ r1
- lib/src/util/async_thunk.dart @ r1
- lib/src/util/dart.dart @ r1
- lib/src/util/io.dart @ r1
- lib/src/util/isolate_wrapper.dart @ r1
- lib/src/utils.dart @ r1
- lib/test.dart @ r1
- pubspec.yaml @ r1
- test/backend/declarer_test.dart @ r1
- test/backend/invoker_test.dart @ r1
- test/frontend/expect_async_test.dart @ r1
- test/frontend/matcher/completion_test.dart @ r1
- test/frontend/matcher/prints_test.dart @ r1
- test/frontend/matcher/throws_test.dart @ r1
- test/frontend/matcher/throws_type_test.dart @ r1
- test/io.dart @ r1
- test/runner/browser/chrome_test.dart @ r1
- test/runner/browser/content_shell_test.dart @ r1
- test/runner/browser/dartium_test.dart @ r1
- test/runner/browser/firefox_test.dart @ r1
- test/runner/browser/internet_explorer_test.dart @ r1
- test/runner/browser/loader_test.dart @ r1
- test/runner/browser/phantom_js_test.dart @ r1
- test/runner/browser/safari_test.dart @ r1
- test/runner/engine_test.dart @ r1
- test/runner/expanded_reporter_test.dart @ r1
- test/runner/isolate_listener_test.dart @ r1
- test/runner/loader_test.dart @ r1
- test/runner/pub_serve_test.dart @ r1
- test/runner/signal_test.dart @ r1
- test/util/multi_channel_test.dart @ r1
- test/util/one_off_handler_test.dart @ r1
- test/util/path_handler_test.dart @ r1
- test/utils.dart @ r1

---

<sup>**[lib/src/runner/browser/compiler_pool.dart, line 107 \[r1\]](https://reviewable.io:443/reviews/dart-lang/test/118#-JpnpsGGbIFU0JJF7QYf)** ([raw file](https://github.com/dart-lang/test/blob/e96b6a8d0dab42f2d3cbfcbdc7d8d5beb956d9b9/lib/src/runner/browser/compiler_pool.dart#L107)):</sup>
At least explain why you do it this way. I think I get it, but it feels weird...

---

<sup>**[lib/src/runner/browser/safari.dart, line 78 \[r1\]](https://reviewable.io:443/reviews/dart-lang/test/118#-JpnoZxXVKCPwmJlOQOP)** ([raw file](https://github.com/dart-lang/test/blob/e96b6a8d0dab42f2d3cbfcbdc7d8d5beb956d9b9/lib/src/runner/browser/safari.dart#L78)):</sup>
`"Failed to start Safari...`

---

<sup>**[lib/src/util/isolate_wrapper.dart, line 10 \[r1\]](https://reviewable.io:443/reviews/dart-lang/test/118#-JpnnduF4Q2esO2h5C5_)** ([raw file](https://github.com/dart-lang/test/blob/e96b6a8d0dab42f2d3cbfcbdc7d8d5beb956d9b9/lib/src/util/isolate_wrapper.dart#L10)):</sup>
Unused.

---

<sup>**[test/runner/isolate_listener_test.dart, line 17 \[r1\]](https://reviewable.io:443/reviews/dart-lang/test/118#-JpnnlcwzgS96RiaaP8w)** ([raw file](https://github.com/dart-lang/test/blob/e96b6a8d0dab42f2d3cbfcbdc7d8d5beb956d9b9/test/runner/isolate_listener_test.dart#L17)):</sup>
unused

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dart-lang/test/118)

**Comment by kevmoo** [comment]
Also: rebase. :-)

---

Review status: all files reviewed, 4 unresolved discussions, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dart-lang/test/118)

**Comment by nex3** [comment]
Review status: all files reviewed, 4 unresolved discussions, some commit checks failed.

---

<sup>**[lib/src/runner/browser/compiler_pool.dart, line 107 \[r1\]](https://reviewable.io:443/reviews/dart-lang/test/118#-JpnpsGGbIFU0JJF7QYf)** ([raw file](https://github.com/dart-lang/test/blob/e96b6a8d0dab42f2d3cbfcbdc7d8d5beb956d9b9/lib/src/runner/browser/compiler_pool.dart#L107)):</sup>
This should be using `invoke()` anyway.

---

<sup>**[lib/src/runner/browser/safari.dart, line 78 \[r1\]](https://reviewable.io:443/reviews/dart-lang/test/118#-JpnoZxXVKCPwmJlOQOP)** ([raw file](https://github.com/dart-lang/test/blob/e96b6a8d0dab42f2d3cbfcbdc7d8d5beb956d9b9/lib/src/runner/browser/safari.dart#L78)):</sup>
Done.

---

<sup>**[lib/src/util/isolate_wrapper.dart, line 10 \[r1\]](https://reviewable.io:443/reviews/dart-lang/test/118#-JpnnduF4Q2esO2h5C5_)** ([raw file](https://github.com/dart-lang/test/blob/e96b6a8d0dab42f2d3cbfcbdc7d8d5beb956d9b9/lib/src/util/isolate_wrapper.dart#L10)):</sup>
Done.

---

<sup>**[test/runner/isolate_listener_test.dart, line 17 \[r1\]](https://reviewable.io:443/reviews/dart-lang/test/118#-JpnnlcwzgS96RiaaP8w)** ([raw file](https://github.com/dart-lang/test/blob/e96b6a8d0dab42f2d3cbfcbdc7d8d5beb956d9b9/test/runner/isolate_listener_test.dart#L17)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dart-lang/test/118)

**Comment by nex3** [comment]
Review status: all files reviewed, 4 unresolved discussions, all commit checks successful.
Reviewed files:
- lib/pub_serve.dart @ r1
- lib/src/backend/declarer.dart @ r1
- lib/src/backend/group.dart @ r1
- lib/src/backend/invoker.dart @ r1
- lib/src/backend/live_test_controller.dart @ r1
- lib/src/executable.dart @ r2
- lib/src/runner/browser/browser_manager.dart @ r2
- lib/src/runner/browser/chrome.dart @ r1
- lib/src/runner/browser/compiler_pool.dart @ r2
- lib/src/runner/browser/content_shell.dart @ r1
- lib/src/runner/browser/dartium.dart @ r1
- lib/src/runner/browser/firefox.dart @ r1
- lib/src/runner/browser/iframe_listener.dart @ r1
- lib/src/runner/browser/internet_explorer.dart @ r1
- lib/src/runner/browser/phantom_js.dart @ r1
- lib/src/runner/browser/safari.dart @ r2
- lib/src/runner/browser/server.dart @ r2
- lib/src/runner/browser/static/host.dart @ r1
- lib/src/runner/engine.dart @ r1
- lib/src/runner/loader.dart @ r2
- lib/src/runner/reporter/compact.dart @ r1
- lib/src/runner/reporter/expanded.dart @ r1
- lib/src/runner/vm/isolate_listener.dart @ r1
- lib/src/runner/vm/isolate_test.dart @ r1
- lib/src/util/async_thunk.dart @ r1
- lib/src/util/dart.dart @ r1
- lib/src/util/io.dart @ r1
- lib/src/util/isolate_wrapper.dart @ r2
- lib/src/utils.dart @ r1
- lib/test.dart @ r1
- pubspec.yaml @ r2
- test/backend/declarer_test.dart @ r1
- test/backend/invoker_test.dart @ r1
- test/frontend/expect_async_test.dart @ r1
- test/frontend/matcher/completion_test.dart @ r1
- test/frontend/matcher/prints_test.dart @ r1
- test/frontend/matcher/throws_test.dart @ r1
- test/frontend/matcher/throws_type_test.dart @ r1
- test/io.dart @ r1
- test/runner/browser/chrome_test.dart @ r1
- test/runner/browser/content_shell_test.dart @ r1
- test/runner/browser/dartium_test.dart @ r1
- test/runner/browser/firefox_test.dart @ r1
- test/runner/browser/internet_explorer_test.dart @ r1
- test/runner/browser/loader_test.dart @ r1
- test/runner/browser/phantom_js_test.dart @ r1
- test/runner/browser/safari_test.dart @ r1
- test/runner/engine_test.dart @ r1
- test/runner/expanded_reporter_test.dart @ r1
- test/runner/isolate_listener_test.dart @ r2
- test/runner/loader_test.dart @ r1
- test/runner/pub_serve_test.dart @ r2
- test/runner/signal_test.dart @ r1
- test/util/multi_channel_test.dart @ r1
- test/util/one_off_handler_test.dart @ r1
- test/util/path_handler_test.dart @ r1
- test/utils.dart @ r1

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dart-lang/test/118)

**Pull request merged**
