### PR TITLE
Stop using deprecated analyzer apis

### PR DESCRIPTION
**Pull request by kevmoo**

### CODE REVIEW

**Comment by nex3** [comment]
I'm not comfortable constraining test to only one major version of `analyzer`. It revs so often and is depended on so widely that this will almost certainly cause version lock and prevent users from upgrading `test`. The deprecation hints aren't causing any harm, and we can easily update in the future when fewer packages are using analyzer versions that don't support the new import scheme.

**Comment by matanlurey** [comment]
These APIs no longer will exist internally - which means we can never update third_party.

**Comment by nex3** [comment]
I suggest re-adding them internally for the time-being, even if they just export the new locations. Removing them seems like a needlessly breaking change.

**Comment by matanlurey** [comment]
You realize we can't roll-back the analyzer internally, ever? It's basically impossible.

**Comment by nex3** [comment]
I'm not suggesting rolling it back, I'm suggesting adding a file in `lib/src/generated/ast.dart` that exports `lib/dart/ast/ast.dart`.

**Comment by matanlurey** [comment]
Is there a guarantee that the APIs are exactly 1:1 (and will continue to be so, forever)?

**Comment by nex3** [comment]
I hope so! If not, how can we safely make this change in test?

**Comment by bwilkerson** [comment]
> I'm suggesting adding a file in lib/src/generated/ast.dart that exports lib/dart/ast/ast.dart.

That file already exists.

Kevin was just trying to remove the uses of the deprecated code before they go away internally because otherwise it will require a multi-step process to get a future version of analyzer rolled internally, which hurts our velocity.

**Comment by nex3** [comment]
What I'm asking is, why are they going away at all? If the APIs still exist, what does it cost to keep the old deprecated filenames around? Removing them is a breaking change, one that concretely affects the biggest user of `analyzer`, and it'll cause a lot of pain.

**Comment by bwilkerson** [comment]
Because we need to draw a clean distinction between the public and private APIs of analyzer, and src/generated is ambiguous.

**Comment by nex3** [comment]
Certainly we shouldn't encourage new users to use it, but there's a substantial concrete benefit to allowing old code to continue using it for a while. That seems to me to outweigh concerns about cleanliness.

**Comment by bwilkerson** [comment]
I'm not sure how long "a while" is :-), but the new location has existed since January 18th. I'm guessing Kevin could have widened the constraints a bit.

**Comment by kevmoo** [comment]
Brian: I actually dug in – I think the lower bound I put is the required
one. Could double-check, though.

**Comment by nex3** [comment]
I basically mean "as long as is feasible". The benefit we get from keeping `test`'s constraint on `analyzer` as wide as possible is very large.

**Comment by kevmoo** [comment]
FWIW – 0.27.2 works – released on Feb 16, 2016

Updated my branch

**Pull request closed without merging**
