### PR TITLE
Declare addTearDownLibrary.

### PR DESCRIPTION
**Pull request by polina-c**
Prerequisite for https://github.com/flutter/flutter/pull/138057.
TODO: add test coverage.

### CODE REVIEW

**Comment by natebosch** [comment]
Why do we need this over `setUpAll` and `addTearDown`?

**Comment by natebosch** [comment]
> > Why do we need this over `setUpAll` and `addTearDown`?
> 
> Because we need it to tear down all tests in the library, not all tests in the group. I do not see other way to traverse to root group. Am i missing something?

I thought  the plan was to intercept the call to `group` and inject the `setUpAll` call?

If we want to avoid that because it's too brittle we can try something like this. I'd go with the name `addTearDownSuite`. @jakemac53 any concerns about such an API?

**Comment by natebosch** [comment]
Ah this isn't user facing either. Should be pretty safe then. Let's  rename to "suite" and add a changelog entry.

**Comment by polina-c** [comment]
> Ah this isn't user facing either. Should be pretty safe then. Let's rename to "suite" and add a changelog entry.

I will be able to use it only with added method `addTearDownSuite` to flutter_test/lib/src/test.compat.dart, that will make it user facing.

Or we can go with how it is currently implemented in https://github.com/flutter/flutter/pull/138057 (intercept the call to group and other user calls), that is little hacky, but not user facing. 

I am ok with both ways.

**Pull request closed without merging**
