### PR TITLE
Require meta 1.1.5 and use @isTest and @isTestGroup to mark test() and group().

### PR DESCRIPTION
**Pull request by scheglov**
See https://github.com/flutter/flutter-intellij/issues/2055 for the context.

### CODE REVIEW

**Comment by jakemac53** [comment]
@scheglov any desired timeline for a release?

**Comment by scheglov** [comment]
I think there is no burning need to publish it, we would have to keep support for not annotated `test()` and `group()` is Analysis Server for some time anyway (for users with older `package:test`). Just publish it at some point :-)

**Comment by jakemac53** [comment]
Ok sounds good, we are publishing fairly often anyways so it should be available within a couple days/weeks.

**Comment by scheglov** [comment]
SG, thanks.

**Pull request merged**
