### PR TITLE
Smoke test analyzer 0.31.0-alpha.0 compatibility.

### PR DESCRIPTION
**Pull request by pq**
FYI @kevmoo 

(Not for landing.)

### CODE REVIEW

**Comment by kevmoo** [comment]
Thank you!

**Comment by pq** [comment]
Looks good to me.  The breakage on Dart `1.23` is unsurprising and I take it not an issue.  Having said that, we should maybe consider upping the Dart SDK constraints for `front_end` to be more than cosmetic (cc @sigmundch) since it can't run on anything less than `1.24`. 

image

**Comment by pq** [comment]
cc @grouma @stereotype441

**Comment by kevmoo** [comment]
Well, in the "real world" I'm guessing pkg/analyzer explicitly restricts 1.23, so this solve won't happen – right?

**Comment by pq** [comment]
> Well, in the "real world" I'm guessing pkg/analyzer explicitly restricts 1.23, so this solve won't happen – right?

Actually no,

    environment:
      sdk: '>=1.20.0 <2.0.0-dev.infinity'

FYI: @bwilkerson --- maybe worth bumping to 1.24.

**Comment by kevmoo** [comment]
Discussed in email...

**Pull request closed without merging**
