### PR TITLE
Fix deprecations and new lints

### PR DESCRIPTION
**Pull request by kevmoo**

### CODE REVIEW

**Comment by natebosch** [comment]
For the future, the commit message would be more useful if it said "Ignore deprecations" instead of "Fix deprecations"...

**Comment by natebosch** [comment]
Do we have an issue filed to stop using those analyzer APIs?

**Comment by kevmoo** [comment]
> For the future, the commit message would be more useful if it said "Ignore deprecations" instead of "Fix deprecations"...

ack

> Do we have an issue filed to stop using those analyzer APIs?

Nope. We'd have to be careful to go through and update the min versions if moving to new APIs

**Comment by natebosch** [comment]
https://github.com/dart-lang/test/issues/1050

**Pull request merged**
