### PR TITLE
rev to analyzer 0.30.0

### PR DESCRIPTION
**Pull request by devoncarew**
- rev to analyzer `0.30.0`
- fix https://github.com/dart-lang/test/issues/592

### CODE REVIEW

**Comment by grouma** [comment]
Note the current Travis tests are broken given the bump in the SDK version. @kevmoo is working through this issue with https://github.com/dart-lang/test/pull/595

**Comment by devoncarew** [comment]
Is that landing soon? I can rebase this PR against master...

**Comment by kevmoo** [comment]
Rebase away...

**Comment by devoncarew** [comment]
Landed; `0.30.0` of analyzer will be published soon.

**Pull request merged**
