### PR TITLE
fix failing casts when talking to minified apps from the host

### PR DESCRIPTION
**Pull request by jakemac53**
Fixes https://github.com/dart-lang/test/issues/2074

This is more a workaround than a true fix, but when talking from a minified dart2js test app to a non-minified host we would get cast failures on these getters. Changing it to an explicit getProperty call and adding the pragma to trust the casts silences the failure.

### CODE REVIEW

**Comment by jakemac53** [comment]
cc @sigmundch

**Review by natebosch — APPROVED** [review]
Should we minify the host app?

Would that have surfaced issues in the test runner communicating with a non-minified test?

**Comment by sigmundch** [comment]
Indeed, minifying the host would have caused failures in an unminified suite. It could also cause issues in a minified suite if they were to pick different names for some types.

FYI the underlying cause is described here: https://github.com/dart-lang/sdk/issues/53154

**Comment by jakemac53** [comment]
I don't think we should minify the host because it will make errors even harder to diagnose

**Pull request merged**
