### PR TITLE
Make tests compatible with Strict CSP

### PR DESCRIPTION
**Pull request by vrana**
This propagates the nonce from any script on the page to the script created by dart.js.

### CODE REVIEW

**Comment by jakemac53** [comment]
Is this different from https://github.com/dart-lang/test/pull/1808?

**Comment by natebosch** [comment]
It looks like #1808 assumes every script must have the `nonce`, while this one allows it on any script element. This one has a matching internal CL that passed presubmit, and I think its more likely to work with custom HTML in case someone has a html file with scripts that have a mix of nonce and not.

**Comment by natebosch** [comment]
Thanks @vrana for sharing the extra info about where we are adding the nonce in our DDC handling. I think we should be able to land this and get it merged into google3

**Review by natebosch — APPROVED** [review]

**Comment by vrana** [comment]
Thanks. Yes, there could be e.g. extensions adding un-nonced scripts breaking the other PR.

**Pull request merged**
